### ISSUE TITLE
possible name collisions if multiple connections

### ISSUE THREAD

**Issue by jakejh** [DalgoT4D/DDP_backend#285]
When creating a connection, the destination schema is set to "staging" and is not editable. There's also no option to add a custom prefix to tables from a given source.

So what happens if multiple sources have an identically named table and airbyte tries to pull them all into that one schema? Even if no collisions, it could be unclear which tables come from which sources.

**Comment by fatchat** [comment]
@siddhant3030 this is a good use case for not freezing Airbyte's destination schema

**Comment by vinod-rajasekaran** [comment]
unsure if it still exists now but airbyte connections allowed for destination table names to have a prefix which should mitigate this - might ned eval on which way is better

**Comment by siddhant3030** [comment]
@jakejh It rarely happens when multiple data have similar names and with the pilots we've done so far I have seen that people can have the same form name in the same source and since we want to make it simple we tell them to change them in the source only. But yeah as Vinod mentioned we can add a prefix to it if we have different connections for each source.

**Comment by fatchat** [comment]
closed via https://github.com/DalgoT4D/webapp/pull/433
